// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
/// 

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-HHJ8B_ZPm5wP85JST5TkYWAq1t7-z8E',
    appId: '1:145567829976:web:417dfb5252baa84d5b2cad',
    messagingSenderId: '145567829976',
    projectId: 'project-foodapp-ct484-6f9cc',
    authDomain: 'project-foodapp-ct484-6f9cc.firebaseapp.com',
    storageBucket: 'project-foodapp-ct484-6f9cc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7Hc1n52vgTbF5gSKkZZQm8h3yRHxdeEA',
    appId: '1:171808292859:android:cdf841f6690e19cb47955e',
    messagingSenderId: '171808292859',
    projectId: 'project-ct484-foodapp',
    storageBucket: 'project-ct484-foodapp.appspot.com',
  );

  
}
